[
    {
        "key": "dbln",
        "value": "%7B%2261586476261731%22%3A%224s6cKgMj%22%7D",
        "domain": "facebook.com",
        "path": "/login/device-based/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.097Z",
        "lastAccessed": "2026-01-12T14:01:01.108Z"
    },
    {
        "key": "datr",
        "value": "ruJkae-ZIbUbPT_Vn3n0pzXh",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.108Z",
        "lastAccessed": "2026-01-12T14:01:01.109Z"
    },
    {
        "key": "sb",
        "value": "ruJkaYI3jOJVOQn3UiSRUWWp",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.109Z",
        "lastAccessed": "2026-01-12T14:01:01.109Z"
    },
    {
        "key": "c_user",
        "value": "61586476261731",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.109Z",
        "lastAccessed": "2026-01-12T14:01:01.109Z"
    },
    {
        "key": "xs",
        "value": "23%3An-VAKV9FotTn3w%3A2%3A1768219339%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.109Z",
        "lastAccessed": "2026-01-12T14:01:01.109Z"
    },
    {
        "key": "pas",
        "value": "61586476261731%3AOVMDMBfI8G",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.109Z",
        "lastAccessed": "2026-01-12T14:01:01.109Z"
    },
    {
        "key": "locale",
        "value": "en_GB",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.109Z",
        "lastAccessed": "2026-01-12T14:01:01.109Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B723x376x3.25",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.109Z",
        "lastAccessed": "2026-01-12T14:01:01.109Z"
    },
    {
        "key": "m_pixel_ratio",
        "value": "3.25",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.109Z",
        "lastAccessed": "2026-01-12T14:01:01.109Z"
    },
    {
        "key": "fbl_st",
        "value": "100638892%3BT%3A29470440",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.109Z",
        "lastAccessed": "2026-01-12T14:01:01.110Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A3049%3Btimestamp%3A1768226401",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.112Z",
        "lastAccessed": "2026-01-12T14:01:01.112Z"
    },
    {
        "key": "fr",
        "value": "0fGpWMgoZTHIkN1yS.AWe888TJjawgaGDPOwkds9400Kb_4YqbCI5MK73q0XkAgVSaQeQ.BpZOKu..AAA.0.0.BpZP5s.AWdjqmYZeuosZR4YJ_VunfnE4do",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.112Z",
        "lastAccessed": "2026-01-12T14:01:01.112Z"
    },
    {
        "key": "wd",
        "value": "980x1885",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.112Z",
        "lastAccessed": "2026-01-12T14:01:01.112Z"
    },
    {
        "key": "dpr",
        "value": "3.25",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.112Z",
        "lastAccessed": "2026-01-12T14:01:01.112Z"
    },
    {
        "key": "presence",
        "value": "C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1768226421540%2C%22v%22%3A1%7D",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-01-12T14:01:01.114Z",
        "lastAccessed": "2026-01-12T14:01:01.114Z"
    }
]
